apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secrets
    namespace: default
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:2SViy90=,iv:iWYAY0Io4bgB+mWuLl/rtym1WulOOHvFeEBUnIxqK7w=,tag:mfjuo7vPP1qOOBoBGHxRrg==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:qXMijWXz578Eh9BpSqRUw2Revwzv/+duTcN05sQMIi0=,iv:mkpI+59rrzn2TbDo0POpEoI9e0KfCCJowNtE+hBvO/8=,tag:18s14kF+F/q9PkpxW/MK1w==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:4fo8TcAnyQUUPt2ZnBmcvayFyVoF2a6kStPOxPe2VXogDs38gH14vatXMmTJqil/9Wun0issHyC0OA==,iv:sU/Z3qE95Gmn0ese9nHlpe5wYtlZnybdhy214ulkeWI=,tag:VRZUOf5H3aU1IUC0iOeZkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQmR5VU5QMTByTitvb1lX
            bzhMN1B6WFVVV09TdXk5UGRJOUNjZUVOQ1FRClUyMGwweVVyRC90dnFGNmxDSmxj
            UDk1eXA1cXh4VERtZGRWRUlFYk9XMm8KLS0tIEJoWS8vV0d6SFQ5Z0ZDYS84S1lq
            c0s5OHFjS3JZUFcwb254cmQ1MHlFNTgKHba2KnWZwrKsjxXZiRuN6V91D1gVjlMw
            F3Xk2glUPko12ubAT2I14DR9+Uv4vgXeYGjLoHv7ExKmY2FUOt/ALA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gte9z7ue3uk3a4088kx3hcsfcww4pdzenufcjcpaxkg225zcsfks4wfnem
    encrypted_regex: ^ZIGBEE2MQTT
    lastmodified: "2026-05-22T11:36:48Z"
    mac: ENC[AES256_GCM,data:x+6msfpG3OECgHQj6SKbOZq9RZavRF9hogMfLwxGZ+Jmhp2Yf5avf3SEn/XIG5Q36t3zoWgCGXfJxREmlnwc4tdGeQBqS74yx7c66DBfgBB+ZGPIo+I6bY/mhT9CK3M6qDmHFvbLQtMDLT+ag7N0Fvt6F6In+kYmh+yzyJo3opI=,iv:3V5eYOZBnpxWyXVsd3UHSJqlSnWe3Z7AcgtJp8gSCrg=,tag:fwKcZp7n2QXphp2pSc/YOw==,type:str]
    version: 3.13.1
