{
 "title": "Homarr Graphs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Sites Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (monitor_status==0)", "legendFormat": "{{ monitor_name }}" }
   ]
  },
  {
   "title": "FluxCD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", ready=\"False\"})",
     "legendFormat": "Home"
    },
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", ready=\"False\"})",
     "legendFormat": "Deskcube"
    },
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", suspended=\"true\"})",
     "legendFormat": "Home S"
    },
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", suspended=\"true\"})",
     "legendFormat": "Deskcube S"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"object\"] == \"qemu\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n//  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_Ws", "legendFormat": "Current" },
    { "expr": "avg_over_time(mystrom_Ws[1d])", "legendFormat": "24h Average" },
    { "expr": "avg_over_time(mystrom_Ws[15m])", "legendFormat": "15m Average" },
    {
     "expr": "nut_http_realpower_nominal/100*nut_http_load",
     "legendFormat": "UPS"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"proxmox.int.sambaum.ch:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Proxmox"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"proxmox2.int.sambaum.ch:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Proxmox 2"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"opnsense.int.sambaum.ch:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "OPNSense"
    }
   ]
  },
  {
   "title": "OPNSense Traffic",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"opnsense.int.sambaum.ch:9100\"}[$__rate_interval]) * 8 / 1014 > 0",
     "legendFormat": "{{device}} recv"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"opnsense.int.sambaum.ch:9100\"}[$__rate_interval]) * 8 / 1024 > 0",
     "legendFormat": "{{device}} trans"
    }
   ]
  },
  {
   "title": "TrueNAS",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(truenas_pool_dataset_usedbysnapshots)",
     "legendFormat": "Snapshots"
    },
    {
     "expr": "truenas_pool_dataset_used{mountpoint=\"/mnt/pool1\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "truenas_pool_dataset_available{mountpoint=\"/mnt/pool1\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}