{
 "title": "My Home Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "operator_namespace",
    "query": {
     "query": "label_values(gotk_reconcile_condition,namespace)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_resource_info,exported_namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   { "name": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   { "name": "Bucket", "query": "buckets()" },
   { "name": "instance", "query": { "query": "label_values(uptime,instance)" } },
   {
    "name": "disk",
    "query": {
     "query": "label_values(disk_io{instance=\"$instance\"},disk)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(interface_io{instance=\"$instance\"},interface)"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(cpu_usage{instance=\"$instance\"},cpu)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "influxdb2_datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage（5m）",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"proxmox.int.sambaum.ch:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Proxmox"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"proxmox2.int.sambaum.ch:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Proxmox 2"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"opnsense.int.sambaum.ch:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "OPNSense"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.35:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Dumpster"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.40:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Deskcube"
    },
    {
     "expr": "avg(irate(cpu_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "TrueNAS"
    }
   ]
  },
  {
   "title": "TrueNAS Disk utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_utilization{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    },
    {
     "expr": "{__name__=~\"truenas_truenas_truenas_disk_stats_busy__serial_lunid_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System runtime",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"proxmox.int.sambaum.ch:9100\"}",
     "legendFormat": "Proxmox"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"proxmox2.int.sambaum.ch:9100\"}",
     "legendFormat": "Proxmox2"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"opnsense.int.sambaum.ch:9100\"}",
     "legendFormat": "OPNSense"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"192.168.1.40:9100\"}",
     "legendFormat": "Deskcube"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"192.168.1.35:9100\"}",
     "legendFormat": "Dumpster"
    },
    {
     "expr": "uptime{instance=~\"$instance\"}",
     "legendFormat": "TrueNAS"
    }
   ]
  },
  {
   "title": "TrueNAS Space",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_pool_dataset_available{mountpoint=\"/mnt/pool1\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "truenas_pool_dataset_used{mountpoint=\"/mnt/pool1\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "FluxCD Failing Reconcilers/Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\", ready=\"False\"})",
     "legendFormat": "Home"
    },
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\", ready=\"False\"})",
     "legendFormat": "Deskcube"
    },
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\", suspended=\"true\"})",
     "legendFormat": "Home S"
    },
    {
     "expr": "count(gotk_resource_info{exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\", suspended=\"true\"})",
     "legendFormat": "Deskcube S"
    }
   ]
  },
  {
   "title": "TrueNAS Disk Temps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "disk_temperature{instance=~\"$instance\"}",
     "legendFormat": "{{serial}}"
    }
   ]
  },
  {
   "title": "Proxmox Storage Pools",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"proxmox\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n"
    },
    {
     "query": "from(bucket: \"proxmox\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"system\")\r\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\r\n  |> filter(fn: (r) => r[\"nodename\"] == \"pve2\")\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with \r\n    _time: r._time,\r\n    _measurement: r.measurement,\r\n    _field: \"used_perc\",\r\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\r\n     }))\r\n  |> drop(columns: [\"avail\",\"used\"])\r\n"
    }
   ]
  },
  {
   "title": "TrueNAS Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "interface_io{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} - {{op}}"
    }
   ]
  },
  {
   "title": "CPU Usage Dumpster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"dumpster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TrueNAS Running S.M.A.R.T Tests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_current_test_percent_done",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power Socket",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_Ws", "legendFormat": "Current" },
    { "expr": "avg_over_time(mystrom_Ws[15m])", "legendFormat": "15m Average" },
    { "expr": "avg_over_time(mystrom_Ws[1d])", "legendFormat": "24h Average" }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "floor(nut_http_runtime/60)", "legendFormat": "Current" }
   ]
  },
  {
   "title": "UPS Power Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "600 / 100 * nut_http_load", "legendFormat": "Current" },
    {
     "expr": "600 / 100 * avg_over_time(nut_http_load[1d])",
     "legendFormat": "24h Average"
    }
   ]
  },
  {
   "title": "OPNSense Network Traffic / sec Receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"opnsense.int.sambaum.ch:9100\"}[$interval]) * 8 / 1014 > 0",
     "legendFormat": "{{device}} recv"
    }
   ]
  },
  {
   "title": "CPU Usage Deskcube",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"deskcube\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 16, "w": 4, "x": 20, "y": 13 } },
  {
   "title": "VM's Root partition usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"192.168.1.35:9100\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"192.168.1.35:9100\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Dumpster"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"192.168.1.40:9100\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"192.168.1.40:9100\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Deskcube"
    }
   ]
  },
  {
   "title": "System temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"proxmox.int.sambaum.ch:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[1d])",
     "legendFormat": "PVE1 CPU (1d)"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"proxmox.int.sambaum.ch:9100\", chip=\"nvme_nvme0\", sensor=\"temp3\"}",
     "legendFormat": "SSD 1"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"proxmox.int.sambaum.ch:9100\", chip=\"nvme_nvme1\", sensor=\"temp3\"}",
     "legendFormat": "SSD 2"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"proxmox.int.sambaum.ch:9100\", chip=\"platform_nct6687_2592\", sensor=\"temp2\"}\t",
     "legendFormat": "System"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"proxmox.int.sambaum.ch:9100\", chip=\"platform_nct6687_2592\", sensor=\"temp4\"}\t",
     "legendFormat": "PCH Chipset"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"proxmox.int.sambaum.ch:9100\", chip=\"platform_nct6687_2592\", sensor=\"temp3\"}\t",
     "legendFormat": "VRM MOS"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"proxmox2.int.sambaum.ch:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[5m])",
     "legendFormat": "PVE2 CPU (5m)"
    },
    {
     "expr": "max(cpu_temperature{instance=~\"$instance\"})",
     "legendFormat": "TrueNAS"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 6, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"object\"] == \"qemu\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n//  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "TLS Min Exp.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(gatus_results_certificate_expiration_seconds)",
     "legendFormat": "{{ monitor_name }}"
    }
   ]
  },
  {
   "title": "Sites Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatus_results_endpoint_success == 0)",
     "legendFormat": "{{ monitor_name }}"
    }
   ]
  },
  {
   "title": "Sites Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (gatus_results_endpoint_success)",
     "legendFormat": "{{ monitor_name }}"
    }
   ]
  }
 ]
}