{
 "title": "MyStrom Power Monitor",
 "tags": [
  "Sam",
  "Starred"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "price", "label": "CHF/KWh", "query": "22.71428571" }
  ]
 },
 "panels": [
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_relay" }
   ]
  },
  {
   "title": "Power Ws",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "mystrom_Ws", "legendFormat": "Watt" }
   ]
  },
  {
   "title": "Power NOW",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_Ws" }
   ]
  },
  {
   "title": "Power",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_Ws", "legendFormat": "Now" },
    {
     "expr": "avg_over_time(mystrom_Ws[$__range])",
     "legendFormat": "Average Range"
    }
   ]
  },
  {
   "title": "CHF per Year",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(24*($A*0.001)*$price/100)*365", "type": "math" },
    { "expression": "(24*($B*0.001)*$price/100)*365", "type": "math" }
   ]
  },
  {
   "title": "CHF per Day",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(24*($A*0.001)*$price/100)", "type": "math" },
    { "expression": "(24*($B*0.001)*$price/100)", "type": "math" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mystrom_temperature", "legendFormat": "Temp" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "mystrom_temperature", "legendFormat": "Temp" }
   ]
  }
 ]
}