{
 "title": "OpnSense Firewall",
 "description": "Dashboard for Prometheus node_exporter on OPNsense",
 "tags": [
  "System",
  "Sam",
  "Starred"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host:",
    "query": {
     "query": "label_values({instance=\"opnsense.int.sambaum.ch:9100\",job=\"opnsense\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "port",
    "query": {
     "query": "label_values(up{job=\"opnsense\"}, instance)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   {
    "name": "cpus",
    "label": "cpus",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=\"opnsense\"}, cpu)"
    }
   },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": {
     "query": "label_values(node_filesystem_size{instance=~\"$instance:$port\"}, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total active Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_active_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$instance\"} ",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "System",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[1m])) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "((node_memory_active_bytes{instance=\"$instance\"} + node_memory_wired_bytes{instance=\"$instance\"}) / node_memory_size_bytes{instance=\"$instance\"}) * 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$instance\",mountpoint=~\"/\"} - node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=~\"/\"}) / node_filesystem_size_bytes{instance=\"$instance\",mountpoint=~\"/\"} * 100",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"} / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "LA / CPU count (1 min average)"
    },
    {
     "expr": "node_load5{instance=\"$instance\"} / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "LA / CPU count (5 min average)"
    },
    {
     "expr": "node_load15{instance=\"$instance\"} / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "LA / CPU count (15 min average)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Network Traffic / sec Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\"}[$interval]) * 8 / 1014 > 0",
     "legendFormat": "{{device}} recv"
    }
   ]
  },
  {
   "title": "Network packets / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$instance\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$instance\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Network Traffic / sec Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\"}[$interval]) * 8 / 1024 > 0",
     "legendFormat": "{{device}} trans"
    }
   ]
  },
  {
   "title": "Mcast packets / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{instance=\"$instance\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{instance=\"$instance\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU ALL usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\", cpu=\"0\"}[$interval])) * 100",
     "legendFormat": "Core 0"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\", cpu=\"1\"}[$interval])) * 100",
     "legendFormat": "Core 1"
    }
   ]
  },
  {
   "title": "CPU Cores Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"0\"}",
     "legendFormat": "core 1"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"1\"}",
     "legendFormat": "core 2"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"2\"}",
     "legendFormat": "core 3"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"3\"}",
     "legendFormat": "core 4"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"4\"}",
     "legendFormat": "core 5"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"5\"}",
     "legendFormat": "core 6"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"6\"}",
     "legendFormat": "core 7"
    },
    {
     "expr": "node_cpu_temperature_celsius{instance=\"$instance\", cpu=\"7\"}",
     "legendFormat": "core 8"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",mountpoint=~\"/\"} - node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=~\"/\"}",
     "legendFormat": "Used {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",mountpoint=~\"/\"}",
     "legendFormat": "Total {{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM detailed allocation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_memory_size_bytes{instance=\"$instance\"}[$interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(node_memory_active_bytes{instance=\"$instance\"}[$interval])",
     "legendFormat": "Active (Used)"
    },
    {
     "expr": "node_memory_cache_bytes{instance=\"$instance\"} + node_memory_buffer_bytes{instance=\"$instance\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_free_bytes{instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_inactive_bytes{instance=\"$instance\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  { "title": "System Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Context switches / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(node_exec_context_switches_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Device interrupts / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "irate(node_exec_device_interrupts_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Device interrupts"
    }
   ]
  },
  {
   "title": "Software interrupts / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "irate(node_exec_software_interrupts_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Software interrupts"
    }
   ]
  },
  {
   "title": "Exec forks() / sec",
   "type": "timeseries",
   "description": "Number of fork() calls / sec",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "irate(node_exec_forks_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Traps / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "irate(node_exec_traps_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "System calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "irate(node_exec_system_calls_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Syscalls"
    }
   ]
  }
 ]
}