{
 "title": "Network UPS Tools",
 "description": "Dashboard for nut-http https://github.com/dietah/nut-http",
 "tags": [
  "ups",
  "NUT",
  "Starred"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Device Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"ups_statusnum\") FROM \"ups\"  fill(null)",
     "select": [
      [
       { "params": [ "ups.status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"ups_statusnum\") FROM \"ups\"  fill(null)",
     "select": [
      [
       { "params": [ "ups.status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"ups_statusnum\") FROM \"ups\"  fill(null)",
     "select": [
      [
       { "params": [ "ups.status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"battery_charge\") FROM \"ups\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery.charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nut_http_charge", "legendFormat": "Charge" }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"ups_load\") FROM \"ups\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nut_http_load", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Runtime on battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_runtime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"battery_runtime\") FROM \"ups\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery.runtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nut_http_runtime", "legendFormat": "Runtime" }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nut_http_battery_voltage" }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "nut_http_battery_voltage", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "Input voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_http_input_voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups_nut",
     "query": "SELECT last(\"input_voltage\") FROM \"ups\" fill(null)",
     "select": [
      [
       { "params": [ "input.voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Input voltage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "nut_http_input_voltage", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "Calculated Power Draw",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "600 / 100 * nut_http_load", "legendFormat": "Current" },
    {
     "expr": "600 / 100 * avg_over_time(nut_http_load[$__range])",
     "legendFormat": "Average Range"
    }
   ]
  },
  {
   "title": "Calculated Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "600 / 100 * nut_http_load", "legendFormat": "Draw" }
   ]
  }
 ]
}