# https://artifacthub.io/packages/helm/headlamp/headlamp

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  releaseName: headlamp
  targetNamespace: default
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      version: '0.40.0'
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        gethomepage.dev/description: Headlamp is a user-friendly Kubernetes UI focused on extensibility
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Other
        gethomepage.dev/icon: headlamp.svg
        gethomepage.dev/name: Headlamp
        gethomepage.dev/pod-selector: app=headlamp
      hosts:
      - host: headlamp.example.com
        paths:
        - path: /
          type: Prefix
      tls:
      - hosts:
        - headlamp.example.com
        secretName: ispin-intdomain-wsop-wildcard-tls
    config:
      pluginsDir: /build/plugins
    volumeMounts:
    - mountPath: /build/plugins
      name: headlamp-plugins
    volumes:
    - name: headlamp-plugins
      emptyDir: {}
    initContainers:
    # Fluxcd Plugin
    - name: headlamp-plugins-flux
      image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
      imagePullPolicy: Always
      command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
      securityContext:
        runAsNonRoot: false
        privileged: false
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
      # Cert-Manager Plugin
    - name: headlamp-plugins-cert-manager
      image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager:latest
      imagePullPolicy: Always
      command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
      securityContext:
        runAsNonRoot: false
        privileged: false
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
