resources:
- ../base
patches:
- target:
    kind: HelmRelease
    name: ingress-nginx
  patch: |-
    - op: replace
      path: /spec/values/controller/service/type
      value: ClusterIP
    - op: remove
      path: /spec/values/controller/service/loadBalancerIP
    - op: add
      path: /spec/values/controller/hostNetwork
      value: true
    - op: add
      path: /spec/values/controller/dnsPolicy
      value: ClusterFirstWithHostNet
    - op: add
      path: /spec/values/tcp
      value:
        "3306": "default/mariadb-idm-service:3306"
        "2222": "default/gitea-service:22"
