apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.21.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 30m
  targetNamespace: cert-manager
  install:
    remediation:
      retries: 3
  timeout: 10m
  values:
    crds:
      enabled: true
