apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: monitoring
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:g0ssP/GNwP5TWP2ncq6vkxSl0kc=,iv:inB4p/P0p63otRBADoUhbo6lYEPoI8RUKKVleIl4yTg=,tag:fWEgQlTEfnxsU3IG/SoJBw==,type:str]
    admin-token: ENC[AES256_GCM,data:+0Qh3YHSw2tj0tcQqrtUChi6lT7+lRWWtRljsg94NaReIN3UmfW1SlM1Up+YTEyOfAUJOxXVLUto9m2yuxSsXOafrT0uD3F4vVB1UdPK2lMJe9NnmfId+DYlgXbPBXMwmEF6kt4g+FRSy1xpepmDHHUqOmD5VqOl,iv:1pPXjuawqZnqHhOgJxl3Msy7306UnU8/vrFVgydAM30=,tag:To+Eciv78Qvnw5c0Sj3k1g==,type:str]
sops:
    age:
        - recipient: age1gte9z7ue3uk3a4088kx3hcsfcww4pdzenufcjcpaxkg225zcsfks4wfnem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbzZvY1ZFOGVXdExiOXZt
            RnJ5eHozT1Z5aWs5WXRCbjIxRXM1YzRYNTFjCmt6clJJLzVtSHBFNDk1RFpvZmFh
            ZzJlbUs3SjdDbUZucm51blJDMWZORHMKLS0tIGhIeEtDSUc0VHg4c2Naa0hHc1FS
            Uk1GQW1XUXNqdHNLVWlnOWJSVjFxVjAKiujBkfl5SqC0JieUYKM7ECJKFR7u4KX0
            VcbieT3DEgq8KWmZD/3xm+VurRBpI1N2QQfPrP5fEVtO99Ycz/FPuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T14:54:38Z"
    mac: ENC[AES256_GCM,data:GkvSkyecMWs/vQ4Y6jouohyfsEfthrZLHQr2xgy1y7eemSmqSpo1Y+B/zncxpvbAvyjfWUM0BXY1DJr48IyCUzrvkBqTSTpxL8gL1bqM26yfftWfDbrrRh7e8VUj3HZXxofeHC0aepd3CJeZ8Nn8aPRvPSkVPRlQPoW6abanrC0=,iv:mutc75pkFc2YAp4qBdo9sdc85ThByOOQwaKetFfl0qU=,tag:V1MCCBrtivKRmY2a99B6ng==,type:str]
    encrypted_regex: ^(admin-password|admin-token)$
    version: 3.12.1
