apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  url: http://influxdb2:80
  jsonData:
    version: Flux
    organization: sam
  secureJsonData:
    token: AKZ0uYE9MduCNeAZ8RDM974Koj0yDiAko1TLjlCUYYJI4YESqBmXA3HEzXtSlsP8p5FS1Wb8ilH0X48i6PrJ4g== # Read-only 
