resources:
- ../../../base/monitoring/influxdb/
patches:
- target:
    kind: HelmRelease
    name: influxdb2
  patch: |-
    - op: replace
      path: /spec/values/ingress/hostname
      value: influxdb.int.sambaum.ch
    - op: replace
      path: /spec/values/ingress/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
