apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- home-assistant-helmrepository.yaml
- home-assistant-release.yaml
- mosquitto.yaml
- zigbee2mqtt.yaml

configMapGenerator:
- name: mosquitto-config
  namespace: default
  files:
  - mosquitto.conf
- name: zigbee2mqtt-config
  namespace: default
  files:
  - configuration.yaml=zigbee2mqtt-configuration.yaml
