resources:
# - change-folder-permissions-job.yaml
# - pv-pvc.yaml
# - helmrepository.yaml
# - release.yaml
- loki.yaml
- promtail.yaml

configMapGenerator:
- name: loki-config
  namespace: monitoring
  files:
  - loki-config.yaml
- name: promtail-config
  namespace: monitoring
  files:
  - promtail-config.yaml
- name: loki-datasource
  namespace: monitoring
  files:
  - loki-datasource.yaml
  options:
    labels:
      grafana_datasource: "1"
