namespace: monitoring

resources:
- loki.yaml
# - promtail.yaml
- alloy.yaml

configMapGenerator:
- name: loki-config
  files:
  - loki-config.yaml
- name: alloy-config
  files:
  - alloy-config.alloy
# - name: promtail-config
#   files:
#   - promtail-config.yaml
- name: loki-datasource
  files:
  - loki-datasource.yaml
  options:
    labels:
      grafana_datasource: "1"
