apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: default
type: Opaque
stringData:
    IMMICH_API_KEY: ENC[AES256_GCM,data:XcP84UJMj2O7cWLbelh6twsZ3/uwrs1hkXJJyBkKcC47hSVmrh84dz2C,iv:Uac1r03w9pkRyI6i8hs0U0ZHcIXc9lW44t9kes+oq9A=,tag:SK3E/2u4QClOl1fvmiUL2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVURIQjVWczB5QVN0Zjdu
            R09aeEtnTFhjM2JqamxDUzZrYkZ6UTgrTEJrCk5NSFZ6RGJ2ZklNajB6c0FjUXR5
            czFsNXpCRHRnRVFoVmpGVEc2T3NDU3MKLS0tIFJncHg0bzJ1bUlkZkI1QTBwZmVK
            RnU1NzQ2bG1YakZWUXhvMUVvZW9TTDAKfHQZVW+q12jkR5thRxrINH2GmhtKSQYr
            BMX0b95ku/6jzWl9/X+RPwh8YsEnD2HAYoW1dSqHr1SklH5kTgPsJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gte9z7ue3uk3a4088kx3hcsfcww4pdzenufcjcpaxkg225zcsfks4wfnem
    encrypted_regex: ^IMMICH_API_KEY$
    lastmodified: "2026-09-06T20:12:06Z"
    mac: ENC[AES256_GCM,data:JQbX3oSCGPNSJYjFNHCw+K/JtoMruvZfhRsfdjUYyaeDYNx544W6IoAosWdAWQMpVDVRdokTJr5JEeX6kFpZLA3qpb8u+sZUnJYQEcbBfosENzXJjThF+cTqoPWnKEZQakXj/Q22I9D/hHndd8pdR97eQTKRG/uLrWDMrcNUtaU=,iv:Bu2ZWhRWLGGWh6lfZkf09/RhyU2YlanNuNkZDJwNZso=,tag:DW0YD8IqGBcBzJAkzTk9TQ==,type:str]
    version: 3.13.2
