apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  storageClassName: openebs-local-hostpath-monitoring-conf
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/conf/monitoring/grafana-pv"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-local-hostpath-monitoring-conf-pvc-grafana
  namespace: monitoring
spec:
  storageClassName: openebs-local-hostpath-monitoring-conf
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: grafana-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  storageClassName: openebs-local-hostpath-monitoring-conf
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/conf/monitoring/prometheus-pv"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-local-hostpath-monitoring-conf-pvc-prometheus
  namespace: monitoring
spec:
  storageClassName: openebs-local-hostpath-monitoring-conf
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: prometheus-pv
