apiVersion: 1
datasources:
- name: Thanos
  type: prometheus
  access: proxy
  url: http://thanos-query:10902
  isDefault: true
  jsonData:
    prometheusType: Thanos
    # customQueryParameters: max_source_resolution=1h
