apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: thanos
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/stevehipwell/helm-charts/thanos
  ref:
    tag: "1.23.0"
