resources:
- ../../../base/default/esphome/

patches:
- target:
    kind: HelmRelease
    name: esphome
  patch: |-
    - op: replace
      path: /spec/values/ingress/main/hosts/0/host
      value: esphome.int.sambaum.ch
    - op: replace
      path: /spec/values/ingress/main/tls/0/hosts/0
      value: esphome.int.sambaum.ch
    - op: replace
      path: /spec/values/ingress/main/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
