resources:
- ../../../base/default/esphome/

patches:
- target:
    kind: Ingress
    name: esphome-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: esphome.int.sambaum.ch
    - op: replace
      path: /spec/tls/0/hosts
      value: [esphome.int.sambaum.ch]
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
