server {
    listen 80;
    root /usr/share/nginx/html;

    types {
        audio/x-mpegurl m3u m3u8;
    }
    default_type application/octet-stream;

    location = / {
        return 302 /playlist.m3u;
    }
}
