apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: default
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:AvvvCuhsIN9zq7/tMfzf2LYSfRnA+9+6dePLMRCJUYToHxIJWE4ShAxjH6Y0lFpvjTYsAnqNnJ0M4r5rUtM15ew2IP29vfVTOjXWihzTzN28XrDjpp0=,iv:0mSWtC0ZpC2ub5OnkgFkT6RzkydD6jts2Yrn9YtjIDU=,tag:W29DsVD/oV9Q5ORd6fuGJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkakxLK0tTQkJ3NzNOY2xa
            WnphbzBrNzlOWXdHWkh1TWpjdThMNzhPVUJnCkp2bnhWejdLaTFnVXpUQXdmdHIx
            Qm1aM1FGSGQwWlg4ZmlaRlFYQlpPSncKLS0tIGFIZGl4RG9aQTdjaFpaU21pVHFM
            a1VnQWl0emI2RDV5MGwzUG1CVnFDbU0K3KK4OjEwP7giozh1HMSPZAg859jJ4JOr
            29krRE55cySqwWTc0Fdx7j0Kauc2xzL2R70FuLfYWOsPKoPQArRomA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gte9z7ue3uk3a4088kx3hcsfcww4pdzenufcjcpaxkg225zcsfks4wfnem
    encrypted_regex: ^PAPERLESS_SECRET_KEY$
    lastmodified: "2026-09-09T14:37:08Z"
    mac: ENC[AES256_GCM,data:F1yhgBFPq+jhawYc2kvRRufWUHuVVK5QYNlOK4DAIHB5m3mgh4hWM6j2Wlo8hXnzGBWBdk8dxVDqdgW+maB9ymZQNy2OV8bgsX0wvBeYdmTNhj3Dpm3YIkgtYwP6E7VxZLBSldVsm9oVi8ZKJJrKwkv6lKh4JUL1wloeIe1/fzg=,iv:mtugu3qgIDFxSiMphAnA0r0SXgIMEyi8ldBQ3xEGmNE=,tag:5jVNtH04bNbyDV4mwtjd/g==,type:str]
    version: 3.13.2
