apiVersion: v1
kind: Secret
metadata:
    name: jsonrpc-rest-bridge-secrets
    namespace: default
stringData:
    BACKEND_API_KEY: ENC[AES256_GCM,data:jExrFyOmuAE3hk4K7zme03DLPxuutz4NUukpDv4vjrB7cr+lB1Z30gAzks88gE6aGqVOSYx0aJIuAoA9CPItmvmk,iv:yn79CqdmXAKO87FtMRjcxX7DWCmqQ/s4NZaKShmNLtg=,tag:AL6p2mNu3WKPAfbub5/I5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ0JLWkF4NnUvbzdZSnZ3
            MGRMUUZ3a0g3cWFqZlgxSWs1ZDRzTUFNbUVnCjBIbWxHN0s4L1d5c0JONFNCYjRS
            MVg1RDhHbjUwalliMjJkcmUvTEh3VjgKLS0tIFJLRHUxKzR1U2hTSUVWdDBuTXFn
            K2RYVXI2aXFYbTlod0FrL3lYUzdqbVEKsgO+pp/f79ylyiiK3lvnboqYgnLVdpNG
            u4wdlq3Q7fn9FykgmnnBjcrKPhFY5A4aXhMfQ9Y2aXzfW/zwcCpsxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gte9z7ue3uk3a4088kx3hcsfcww4pdzenufcjcpaxkg225zcsfks4wfnem
    encrypted_regex: ^(stringData).*$
    lastmodified: "2026-09-21T08:47:26Z"
    mac: ENC[AES256_GCM,data:X4oKIjbDXPts2v2Tb0RK8HdAoU5Y4xDu/37tlVV4vIOQXa8ykLXxkdS+7FiqRetk+EsEdAZeUokybdPfQ7oE6VMoq5AcdAYXPVDjI6cqb/G6dGD3+h2SGqs8P8ESVRPbV5pr9k2HXJ2UXidI10aFbjol+y1hkqFd7Z1D/udAfGQ=,iv:lmTGq7aBEda5iqmNSIdw+sU5vNtxzQucv/I2EQ4q1wc=,tag:bq8D2KPCfRjVVAlBN8eLBg==,type:str]
    version: 3.13.3
