apiVersion: v1
kind: Secret
metadata:
    name: overleaf-secrets
    namespace: default
type: Opaque
stringData:
    OVERLEAF_INVITE_TOKEN_SECRET: ENC[AES256_GCM,data:6FX+YUIWPg7oKsMeZpsTL8Op2zwJ5qtSHqGcPpmzuckcVWXZN1d7KlZUKqM=,iv:8WBgychj4llD9n1choAtKrAf67nyLu5nlzLxAAaFMq0=,tag:mFCggVFx9aAqAAQfYjg2SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRDFIUG1oSkNtNGl3REVD
            UW9iK2trRG50aWpjdTd1MzlUZ0huVm9SZmswCnBOZ1p6bmthT1V2Qll3QVMzVHJM
            akVxVzVicW4yR0tUK0tuSlNJOXZYbE0KLS0tIEkydjJQWFZic0VhR1FWeFZ1L0x6
            MVBhbWNsY0RHc0JEOENvL1UxY0NIRTAKDj+mDu5N0iSL6wik+gB6ZNDxsPqgkEqL
            UCR1jUqOxUJd2lLqxz7DoPOM/3E1gR2CzU27jzIZ2qFvxjZy/2Bn0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gte9z7ue3uk3a4088kx3hcsfcww4pdzenufcjcpaxkg225zcsfks4wfnem
    encrypted_regex: ^OVERLEAF_INVITE_TOKEN_SECRET$
    lastmodified: "2026-08-19T08:50:08Z"
    mac: ENC[AES256_GCM,data:/P+JDPTJZxMeIq91Tgm75J4elnTGt6QBnkDz80xCk8+c6m7MKg19id3sgvORNOLMatpsSm8xJ8lgdA/Mdeml9lZq21Y7Lp0QchAJRTNiJhctnbbNMaM26mRCBJq+nZTayQ4gQamQIMCIKFN87TccJFRQmZv35B9ef6rjxzUIHJo=,iv:SQJAtzs6v0pV9UI4wQqipv+V3PXibjhy7DsFBgNaLe8=,tag:QQ9kyJ288QHjc7UtND6cxA==,type:str]
    version: 3.13.1
